name: Deploy to Koyeb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Deploy to Koyeb
        uses: koyeb-community/koyeb-actions@v2
        with:
          api-token: ${{ secrets.KOYEB_API_TOKEN }}
          app-name: sistem-ticket
          service-name: api-service
          service-ports: 8080:http
          service-env: |
            DB_USERNAME=EventSphere_owner
            DB_PASSWORD=npg_2QiwmupIb7UX
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CORS_ALLOWED_ORIGIN=${{ secrets.CORS_ALLOWED_ORIGIN }}
          docker-build: true
          docker-build-context: .
          docker-build-args: |
            JAR_FILE=build/libs/sistem-ticket-0.0.1-SNAPSHOT.jar
